// The roster. Ids are the gateway contract's `personas[]` values; the gateway owns
// the persona bible (prompts never ship to the client). Sources are public domain.
// No Jesus in v1 (build spec, 2026-10-07). Monograms, never portraits — the
// Montessori estate's non-affiliation line depends on it.

export interface Persona {
  id: string
  name: string
  /** Stylised monogram — initials, not a face. */
  monogram: string
  /** One line: what they bring to the table. */
  brings: string
  /** Public-domain source the gateway's persona bible is built from. */
  source: string
  /** Ticked on first load. */
  defaultOn: boolean
}

export const MAX_PERSONAS = 4

export const PERSONAS: Persona[] = [
  {
    id: 'socrates',
    name: 'Socrates',
    monogram: 'ΣΩ',
    brings: 'Asks the question you are avoiding, then asks it again.',
    source: "Plato's dialogues (Jowett translation)",
    defaultOn: true,
  },
  {
    id: 'marcus-aurelius',
    name: 'Marcus Aurelius',
    monogram: 'MA',
    brings: 'Strips the idea down to what is actually in your control.',
    source: 'Meditations (Long translation)',
    defaultOn: true,
  },
  {
    id: 'seneca',
    name: 'Seneca',
    monogram: 'LS',
    brings: 'Counts the cost in time and money before anyone counts the upside.',
    source: 'Letters to Lucilius (Gummere translation)',
    defaultOn: true,
  },
  {
    id: 'buddha',
    name: 'Buddha',
    monogram: 'SG',
    brings: 'Names the attachment driving the plan.',
    source: 'Pali Canon (Rhys Davids translation)',
    defaultOn: false,
  },
  {
    id: 'confucius',
    name: 'Confucius',
    monogram: 'KF',
    brings: 'Weighs duty, relationships and who carries the work.',
    source: 'Analects (Legge translation)',
    defaultOn: false,
  },
  {
    id: 'franklin',
    name: 'Benjamin Franklin',
    monogram: 'BF',
    brings: 'Turns the idea into a cheap experiment you can run this week.',
    source: 'Autobiography; Poor Richard’s Almanack',
    defaultOn: false,
  },
  {
    id: 'montessori',
    name: 'Maria Montessori',
    monogram: 'MM',
    brings: 'Asks what the user learns by doing, not by being told.',
    source: 'The Montessori Method (1912 translation)',
    defaultOn: false,
  },
]

export const PERSONA_BY_ID = new Map(PERSONAS.map((p) => [p.id, p]))

/**
 * Ticking rules: up to MAX_PERSONAS at once, never an empty council. Pure so the
 * cap has a test that does not need a rendered picker.
 */
export function nextPicked(current: string[], id: string): string[] {
  if (current.includes(id)) {
    return current.length > 1 ? current.filter((p) => p !== id) : current
  }
  return current.length >= MAX_PERSONAS ? current : [...current, id]
}

export const DEFAULT_PERSONA_IDS = PERSONAS.filter((p) => p.defaultOn).map((p) => p.id)

/** Fallback for a persona id the gateway sends that this build doesn't know. */
export function personaName(id: string): string {
  return PERSONA_BY_ID.get(id)?.name ?? id
}

export function personaMonogram(id: string): string {
  return PERSONA_BY_ID.get(id)?.monogram ?? id.slice(0, 2).toUpperCase()
}

export const DISCLOSURE =
  'A fictional interpretation of historical thinkers, generated by AI. Not the words or ' +
  'opinions of the real people, and not medical, legal or financial advice.'

export const MONTESSORI_NOTE =
  'Not affiliated with, or endorsed by, any Montessori organisation or estate.'
