// The roster. Ids are the gateway contract's `personas[]` values; the gateway owns
// the persona bible (prompts never ship to the client). Sources are public domain.
// No Jesus in v1 (build spec, 2026-10-07). Monograms, never portraits — the
// Montessori estate's non-affiliation line depends on it.

export interface Persona {
  id: string
  name: string
  /** Stylised monogram — initials, not a face. */
  monogram: string
  /** One line: what they bring to the table. */
  brings: string
  /** Public-domain source the gateway's persona bible is built from. */
  source: string
  /** Ticked on first load. */
  defaultOn: boolean
}

export const MAX_PERSONAS = 4

export const PERSONAS: Persona[] = [
  {
    id: 'socrates',
    name: 'Socrates',
    monogram: 'ΣΩ',
    brings: 'Asks the question you are avoiding, then asks it again.',
    source: "Plato's dialogues (Jowett translation)",
    defaultOn: true,
  },
  {
    id: 'marcus-aurelius',
    name: 'Marcus Aurelius',
    monogram: 'MA',
    brings: 'Strips the idea down to what is actually in your control.',
    source: 'Meditations (Long translation)',
    defaultOn: true,
  },
  {
    id: 'seneca',
    name: 'Seneca',
    monogram: 'LS',
    brings: 'Counts the cost in time and money before anyone counts the upside.',
    source: 'Letters to Lucilius (Gummere translation)',
    defaultOn: true,
  },
  {
    id: 'buddha',
    name: 'Buddha',
    monogram: 'SG',
    brings: 'Names the attachment driving the plan.',
    source: 'Pali Canon (Rhys Davids translation)',
    defaultOn: false,
  },
  {
    id: 'confucius',
    name: 'Confucius',
    monogram: 'KF',
    brings: 'Weighs duty, relationships and who carries the work.',
    source: 'Analects (Legge translation)',
    defaultOn: false,
  },
  {
    id: 'franklin',
    name: 'Benjamin Franklin',
    monogram: 'BF',
    brings: 'Turns the idea into a cheap experiment you can run this week.',
    source: 'Autobiography; Poor Richard’s Almanack',
    defaultOn: false,
  },
  {
    id: 'montessori',
    name: 'Maria Montessori',
    monogram: 'MM',
    brings: 'Asks what the user learns by doing, not by being told.',
    source: 'The Montessori Method (1912 translation)',
    defaultOn: false,
  },
]

// v4 Business roster (flywheel/docs/expansion/council-v4.md "Rosters"). Drucker, Jobs and
// Grove are not public domain: the gateway grounds them in documented ideas and a short
// attributed quote bank, and the app labels each "simulation inspired by …".
export interface Adviser extends Persona {
  /** Shown under the name in the picker; set for the non-public-domain advisers. */
  inspiredBy?: string
}

export const BUSINESS: Adviser[] = [
  {
    id: 'drucker',
    name: 'Drucker',
    monogram: 'PD',
    brings: 'Asks whose circumstances improve, and how you would know.',
    source: 'The Practice of Management; The Effective Executive (ideas, short quotes)',
    defaultOn: true,
    inspiredBy: 'Peter Drucker',
  },
  {
    id: 'jobs',
    name: 'Jobs',
    monogram: 'SJ',
    brings: 'Makes it tangible: what someone would see and do.',
    source: 'Documented product decisions, interviews (ideas, short quotes)',
    defaultOn: true,
    inspiredBy: 'Steve Jobs',
  },
  {
    id: 'grove',
    name: 'Grove',
    monogram: 'AG',
    brings: 'Execution, owners, and the evidence that would change course.',
    source: 'High Output Management; Only the Paranoid Survive (ideas, short quotes)',
    defaultOn: true,
    inspiredBy: 'Andy Grove',
  },
  { ...PERSONAS[0], defaultOn: true },
]

export const FACILITATOR = { id: 'facilitator', name: 'Facilitator', monogram: 'F' }

export type RosterId = 'business' | 'classics'

export const ROSTERS: Record<RosterId, Adviser[]> = { business: BUSINESS, classics: PERSONAS }

/** Who is ticked when a roster is chosen: all four for Business, the v3 three for Classics. */
export function defaultAdvisers(roster: RosterId): string[] {
  return ROSTERS[roster].filter((p) => p.defaultOn).map((p) => p.id)
}

export const BUSINESS_DISCLOSURE =
  'Simulations inspired by the documented ideas and work of real people, generated by AI. ' +
  'Not their words, opinions or endorsement, and not medical, legal or financial advice.'

export const PERSONA_BY_ID = new Map<string, { name: string; monogram: string }>(
  [...PERSONAS, ...BUSINESS.slice(0, 3), FACILITATOR].map((p) => [p.id, p]),
)

/**
 * Ticking rules: up to MAX_PERSONAS at once, never an empty council. Pure so the
 * cap has a test that does not need a rendered picker.
 */
export function nextPicked(current: string[], id: string): string[] {
  if (current.includes(id)) {
    return current.length > 1 ? current.filter((p) => p !== id) : current
  }
  return current.length >= MAX_PERSONAS ? current : [...current, id]
}

export const DEFAULT_PERSONA_IDS = PERSONAS.filter((p) => p.defaultOn).map((p) => p.id)

/** Fallback for a persona id the gateway sends that this build doesn't know. */
export function personaName(id: string): string {
  return PERSONA_BY_ID.get(id)?.name ?? id
}

export function personaMonogram(id: string): string {
  return PERSONA_BY_ID.get(id)?.monogram ?? id.slice(0, 2).toUpperCase()
}

export const DISCLOSURE =
  'A fictional interpretation of historical thinkers, generated by AI. Not the words or ' +
  'opinions of the real people, and not medical, legal or financial advice.'

export const MONTESSORI_NOTE =
  'Not affiliated with, or endorsed by, any Montessori organisation or estate.'
